FROM ubuntu

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3 

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

RUN export FLASK_ENV="development" \ export FLASK_APP="main:app"

COPY . /app

ENTRYPOINT [ "python3" ]

CMD [ "flask run" ]