"""empty message

Revision ID: eea0a417ec30
Revises: 
Create Date: 2021-11-15 20:41:00.336903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea0a417ec30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('user_id_seq')"), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('num', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('news', sa.String(length=50), nullable=True),
    sa.Column('safe_title', sa.String(length=100), nullable=False),
    sa.Column('transcript', sa.String(length=500), nullable=False),
    sa.Column('alt', sa.String(length=500), nullable=False),
    sa.Column('img', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('day', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('user_id_seq')"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('comic')
    # ### end Alembic commands ###
